### ISSUE TITLE
Connecting to Xiaomi Gateway...

### ISSUE THREAD

**Issue by yceballost** [mirko3000/MMM-xiaomi#20]
Hi,

This message appears and still in the screen

`Connecting to Xiaomi Gateway`

I'm using this gateway
![Screenshot 2021-03-27 at 19 21 36](https://user-images.githubusercontent.com/6722153/112730410-ac311780-8f31-11eb-8b23-c82266b1fcad.png)

And this is my config
```
    {
      module: 'MMM-xiaomi',
      position: 'bottom_right',
      header: '',
      config: {
        gatewayIP: '192.168.1.64',
	  	gatewayToken: '6c50484e46394953426fXXXXXXXXXXXX',
        animationSpeed: 1000,
        graphicLayout: false,
        updateInterval: 30,
        showHeating: false,
        showWindow: false,
        showVentilation: true,
        showLights: false,
        showTrend: true,
        showNotifications: true,
        audioNotifications: false,
        minTemperature: 17,
        maxTemperature: 23,
        maxHumidity: 68,
        celcius: true
        }
    },
```

**Comment by Moerup** [comment]
I have the same Gateway and mine is also stuck on the same.
How did you get the gatewayToken?

**Comment by yceballost** [comment]
I got it with this app
https://github.com/Maxmudjon/Get_MiHome_devices_token/releases

**Comment by Moerup** [comment]
When running MagicMirror with dev enabled I get the following log messages from the module:

`[07.04.2021 21:28.41.916] [LOG]   Wed Apr 07 2021 21:28:41 GMT+0200 (Central European Summer Time): Triggering Xiaomi Gateway connect`

`[07.04.2021 21:28.54.094] [ERROR] Error: Call to device timed out
    at Timeout.retry [as _onTimeout] (/home/pi/MagicMirror/modules/MMM-xiaomi/node_modules/miio/lib/device.js:225:18)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) {
  code: 'timeout'
}
`

Let me know if you need anything else to debug it :)

**Comment by mag999DK** [comment]
Hi

Did you find a solution? I have the same problem.
I use Xiaomi gateway v3 on de server.

**Comment by Moerup** [comment]
Nope, tried a lot to get it working. Different libraries and editing the code, but still can't get it to work.

**Comment by mag999DK** [comment]
I think it is possible if you downgrade the firmware, but it is difficult.
I will order a gateway 2 and hope it works.
