### ISSUE TITLE
Error: Cannot find module 'node-aplay'

### ISSUE THREAD

**Issue by smotx** [mirko3000/MMM-xiaomi#8]
Hi,

anyone know why this module need aplay ?

`Error: Cannot find module 'node-aplay'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-xiaomi/node_helper.js:11:20)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-xiaomi/node_helper.js:140:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
Whoops! There was an uncaught exception...
`

Thanks for help

**Comment by mirko3000** [comment]
It needs aplay to play a sound on warnings (low temperature or high humidity). Where are you getting the error?

**Comment by smotx** [comment]
perhaps because aplay use by another module ? (Alexa)

**Comment by mirko3000** [comment]
As said, I used it to play audio notifications. Did you install via npm install?
